### ISSUE TITLE
Error building IC 

### ISSUE THREAD

**Issue by bernardcraddock** [aakash-s45/ic#4]
Hi @aakash-s45 ,

Today i thought i'd take chance and see if i can build and run IC master branch on Ubuntu 20.04.5 using both linux and chrome .
the build failed as follows and i have a couple of questions 

1. is this just something simple I'm missing or wrong branch or  does IC require build and run on AGL?
2. If requires AGL have or will you document IC AGL install and build steps?
3. Will you continue IC development after GSoc completion or are you done when GSoc completes?
4.  Can you request https://github.com/meta-flutter/meta-flutter/issues  to include IC, that way i think I should be able to run it without AGL

please advise
Best regards

/ **************** Linux****************/

parallels > flutter run
Multiple devices found:
Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.5 LTS 5.15.0-46-generic
Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125
[1]: Linux (linux)
[2]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 1
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           

** (ic:9849): CRITICAL **: 15:48:50.580: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (ic:9849): CRITICAL **: 15:48:50.587: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found
Syncing files to device Linux...                                    87ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:33505/1EoN3OJoCoQ=/
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: Cannot open file, path = '/etc/default/openroutekey' (OS Error: No such file or directory, errno = 2)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: Cannot open file, path = '/etc/xdg/AGL/flutter-cluster-dashboard.yaml' (OS Error: No such file or directory, errno = 2)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
<asynchronous suspension>

The Flutter DevTools debugger and profiler on Linux is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:33505/1EoN3OJoCoQ=/
Lost connection to device.

(ic:9849): GLib-GObject-WARNING **: 15:49:34.660: ../../../gobject/gsignal.c:2736: instance '0x2121c00' has no handler with id '254'

/ **************** Web ****************/

parallels > flutter run
Multiple devices found:
Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.5 LTS 5.15.0-46-generic
Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125
[1]: Linux (linux)
[2]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 2
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             19.3s
This app is linked to the debug service: ws://127.0.0.1:44361/ErYRuY5xBkQ=/ws
Debug service listening on ws://127.0.0.1:44361/ErYRuY5xBkQ=/ws

💪 Running with sound null safety 💪

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:44361/ErYRuY5xBkQ=
Flutter Web Bootstrap: Programmatic
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:44361/ErYRuY5xBkQ=
Error: Unsupported operation: default SecurityContext getter
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49        throw_
dart-sdk/lib/_internal/js_dev_runtime/patch/io_patch.dart 579:5                     get defaultContext
packages/flutter_cluster_dashboard/vehicle_signal/vehicle_signal_config.dart 17:41  initializeClient
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                  <fn>
dart-sdk/lib/async/zone.dart 1653:54                                                runUnary
dart-sdk/lib/async/future_impl.dart 147:18                                          handleValue
dart-sdk/lib/async/future_impl.dart 766:44                                          handleValueCallback
dart-sdk/lib/async/future_impl.dart 795:13                                          _propagateToListeners
dart-sdk/lib/async/future_impl.dart 566:5                                           [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 639:7                                           callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                                    _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                                     _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15                 <fn>
Flutter Web Bootstrap: Programmatic

**Comment by aakash-s45** [comment]
Hi Bernard,
1. Error is because of two missing files. First one is the config file and second one is used for the openrouteservice API key. IC app requires Kuksa server and these two files. So yes, we need AGL to run this app. But if you want to run without AGL then you can checkout the README file. It is updated now.
2. Yes, I have added the documentation to build and boot the AGL image with instrument cluster app. Checkout [here](https://docs.automotivelinux.org/en/master/#0_Getting_Started/3_Build_and_Boot_guide_Profile/2_Flutter_Instrument_Cluster_%28qemu-x86%29/)
3. I am planning to keep  developing this app.
4.  You can run it without AGL. Please check README 
 
if you find any issues please inform, I'll try to resolve.

regards

**Comment by bernardcraddock** [comment]
Hi Aakash,
thanks for the update much appreciated, and very nice to hear you're going to continue post GSoc as Pumped needs an IC app to integrate with on low oil, fuel, tyre pressure, battery etc.

Your build your own steps are a little involved at the moment, so in coming days i'll start with the AGL build, and see how i go yes i'll ping you should i encounter any issues.

Couple of other points
1. what machine architecture and OS release is your build server
2. Are you using the same build server for both AGL/IC and  build your own linux/IC ?
3. Is it ok to use AGL master branch (tip of tree)  or did you lock in a specific release ?

regards

**Comment by aakash-s45** [comment]
HI,
1. For AGL, I use a build server provided by my mentor. It is a debian based server.
2. debian build server for AGL and MacOS Monterey on M1 machine for flutter apps development. I also tested ic app on Ubuntu 20.
3. Yes, you can use AGL master branch.

**Comment by bernardcraddock** [comment]
Hi ,
All built and running thanks

**Comment by aakash-s45** [comment]
Hi, Thanks for testing and feedback.
